Update python-package-conda.yml

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -1,34 +1,46 @@
-name: Python Package using Conda
-
-on: [push]
+name: Daily Update
+on:
+  schedule:
+    - cron: '45 21 * * *'
+  workflow_dispatch:
+    branches:
+      - main
 
 jobs:
-  build-linux:
+  run_script:
     runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 5
-
+    defaults:
+      run:
+        working-directory: ${{ github.workspace }}  # 显式指定工作目录
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: '3.10'
-    - name: Add conda to system path
-      run: |
-        # $CONDA is an environment variable pointing to the root of the miniconda directory
-        echo $CONDA/bin >> $GITHUB_PATH
-    - name: Install dependencies
-      run: |
-        conda env update --file environment.yml --name base
-    - name: Lint with flake8
-      run: |
-        conda install flake8
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest
-      run: |
-        conda install pytest
-        pytest
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Verify environment.yml
+        run: |
+          ls -la
+          if [ ! -f "environment.yml" ]; then
+            echo "File not found in $PWD"
+            exit 1
+          fi
+
+      - name: Set up Conda
+        uses: conda-incubator/setup-miniconda@v4
+        with:
+          activate-environment: base
+          python-version: 3.10
+
+      - name: Update environment
+        run: conda env update --file environment.yml --name base
+
+      - name: Run script and commit
+        run: |
+          python main.py
+          git config --global user.name "GitHub Actions"
+          git add .
+          git commit -m "Auto-update" || echo "No changes"
+          git push
+        env:
+          TZ: Asia/Shanghai
